Update test-json-env.yaml

diff --git a/.github/workflows/test-json-env.yaml b/.github/workflows/test-json-env.yaml
--- a/.github/workflows/test-json-env.yaml
+++ b/.github/workflows/test-json-env.yaml
@@ -16,17 +16,17 @@ jobs:
           url: ${{ secrets.ENV_URL }}
           token: ${{ secrets.ENV_TOKEN }}
 
-      - name: Ensure required env vars exist
-        run: |
-          REQUIRED_VARS=("NODE_ENV" "database_host" "database_password")
-          for VAR in "${REQUIRED_VARS[@]}"; do
-            if [ -z "${!VAR:-}" ]; then
-              echo "❌ $VAR is missing!"
-              exit 1
-            else
-              echo "✅ $VAR is present"
-            fi
-          done
+      # - name: Ensure required env vars exist
+      #   run: |
+      #     REQUIRED_VARS=("NODE_ENV" "database_host" "database_password")
+      #     for VAR in "${REQUIRED_VARS[@]}"; do
+      #       if [ -z "${!VAR:-}" ]; then
+      #         echo "❌ $VAR is missing!"
+      #         exit 1
+      #       else
+      #         echo "✅ $VAR is present"
+      #       fi
+      #     done
 
       - run: |
           echo "$database_host"
